version: '3.8'

services:
  frontend:
    build:
      context: ./DiabetesTrackingApp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./DiabetesTrackingApp/src:/app/src
      - ./DiabetesTrackingApp/public:/app/public

  backend:
    build:
      context: ./DiabetesMonitoringSystem
      dockerfile: Dockerfile
    container_name: diabetes_api
    ports:
      - "7014:7014"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=DiabetesDb;Username=postgres;Password=vavi
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=DiabetesDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vavi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: