version: '3.8'

services:
  frontend:
    build:
      context: ./DiabetesTrackingApp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./DiabetesMonitoringSystem
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=DiabetesDb;Username=postgres;Password=vavi
      - Cors__FrontendOrigin=http://frontend:80
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=DiabetesDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vavi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: